name: hackkings
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.6.1
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - astor=0.7.1
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.0.2
  - c-ares=1.15.0
  - ca-certificates
  - certifi=2018.10.15
  - cffi=1.11.5
  - chardet=3.0.4
  - cloudpickle=0.6.1
  - cryptography=2.4.1
  - cycler=0.10.0
  - decorator=4.3.0
  - entrypoints=0.2.3
  - freetype=2.9.1
  - gast=0.2.0
  - grpcio=1.16.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.7
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0
  - ipython=7.1.1
  - ipython_genutils=0.2.0
  - jedi=0.13.1
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - keras-applications=1.0.6
  - keras-preprocessing=1.0.5
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.2
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.35
  - libprotobuf=3.6.1
  - libsodium=1.0.16
  - libxml2=2.9.8
  - libxslt=1.1.3
  - lxml=4.2.5
  - markdown=3.0.1
  - markupsafe=1.1.0
  - matplotlib=3.0.1
  - mistune=0.8.4
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - pandas=0.23.4
  - pandas-datareader=0.7.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - patsy=0.5.1
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=18.1
  - plotly=3.4.2
  - prometheus_client=0.4.2
  - prompt_toolkit=2.0.7
  - protobuf=3.6.1
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.3.0
  - pysocks=1.6.8
  - python=3.6.7
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pyzmq=17.1.2
  - readline=7.0
  - requests=2.20.1
  - retrying=1.3.3
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.6.2
  - six=1.11.0
  - sqlite=3.25.3
  - statsmodels=0.9.0
  - tensorboard=1.12.0
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - urllib3=1.23
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.32.3
  - wrapt=1.10.11
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - inflection==0.3.1
    - kaggle==1.5.0
    - more-itertools==4.3.0
    - mpl-finance==0.10.0
    - python-slugify==1.2.6
    - quandl==3.4.5
    - tqdm==4.28.1
    - unidecode==1.0.23

